<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $options
 */

// Can be used directly with an item or through media file rendering, so some checks are added.

$resource = $resource ?? null;
$options = $this->prepareModelViewer($resource, $options ?? []);
if (is_null($options)) {
    return;
}

$optionsJson = json_encode($options, 448);
$script = <<<JS
if (typeof modelViewerOptions === 'undefined') {
    var modelViewerOptions = [];
}
modelViewerOptions.push($optionsJson);
JS;
$this->headScript()
    ->appendScript($script);
?>

<?php if (!empty($options['heading'])): ?>
    <h2><?= $options['heading'] ?></h2>
<?php endif; ?>

<div id="<?= $options['id'] ?>" <?= $options['attributes'] ?? 'class="threejs" allowfullscreen="allowfullscreen" style="height: 600px; height: 70vh;"' ?>><canvas></canvas></div>
