<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $options
 *
 * @see https://discoverthreejs.com/book/introduction/get-threejs/
 */

// Can be used directly with an item or through media file rendering, so some checks are added.

$resource = $resource ?? null;
$options = $this->prepareModelViewer($resource, $options ?? []);
if (is_null($options)) {
    return;
}

$optionsJson = json_encode($options, 448);
$optionsJs = <<<JS
if (typeof modelViewerOptions === 'undefined') {
    var modelViewerOptions = [];
}
modelViewerOptions.push($optionsJson);
JS;
$this->headScript()
    ->appendScript($optionsJs);

// User attribute names and values are already escaped.
$attrs = '';
foreach ($options['attributes'] as $name => $value) $attrs .= ' ' . $name . '="' . $value . '"';
?>

<?php if (!empty($options['heading'])): ?>
    <h2><?= $options['heading'] ?></h2>
<?php endif; ?>

<div id="<?= $options['id'] ?>"<?= $attrs ?>><canvas></canvas></div>
